name: alarmapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_native_splash: ^2.4.1
  animated_splash_screen: ^1.3.0
  intl: ^0.19.0
  audioplayers: ^6.1.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/clock.jpg
    - assets/alarm.mp3
    - assets/alarm1.mp3
    - assets/alarm2.mp3
